theme: jekyll-theme-minimal
title: ERC-7866 Decentralised User Profiles
description: A production-ready standard for decentralized, interoperable user profiles on EVM blockchains
github:
  repository_url: https://github.com/anistark/erc7866
